# Generated by Django 6.0.2 on 2026-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('Appointment Scheduled', 'Appointment Scheduled'), ('Qualified to Buy', 'Qualified to Buy'), ('Presentation Scheduled', 'Presentation Scheduled'), ('Decision Maker Bought In', 'Decision Maker Bought In'), ('Contract Sent', 'Contract Sent'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Appointment Scheduled', max_length=50)),
                ('close_date', models.DateField()),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
            ],
        ),
    ]
