# Generated by Django 6.0.2 on 2026-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Waiting on us', 'Waiting on us'), ('Waiting on contact', 'Waiting on contact'), ('Closed', 'Closed')], default='New', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('source', models.CharField(choices=[('Chat', 'Chat'), ('Email', 'Email'), ('Phone', 'Phone')], default='Email', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('associated_deal', models.CharField(blank=True, max_length=200)),
                ('associated_company', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
