# Generated by Django 6.0.2 on 2026-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Qualified Lead', 'Qualified Lead'), ('Lost', 'Lost'), ('Bad Info', 'Bad Info')], default='New', max_length=30),
        ),
    ]
