# Generated by Django 6.0.2 on 2026-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Qualified', 'Qualified'), ('Qualified Lead', 'Qualified Lead'), ('Lost', 'Lost'), ('Bad Info', 'Bad Info'), ('Converted', 'Converted')], default='New', max_length=30),
        ),
    ]
